Fix a compile-time warning/error with C++ compiler
The error is as follows:
```
In file included from /home/alex/src/xxx/src/motor_task.cpp:19:
/home/alex/src/xxx/tmc/tmc/ic/TMC2209/TMC2209.h:40:13: error: narrowing conversion of '3238854692' from 'unsigned int' to 'int32_t' {aka 'long int'} [-Wnarrowing]
   40 | #define R70 0xC10D0024  // PWMCONF
      |             ^~~~~~~~~~
/home/alex/src/xxx/tmc/tmc/ic/TMC2209/TMC2209.h:73:9: note: in expansion of macro 'R70'
   73 |         R70, 0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0  // 0x70 - 0x7F
      |         ^~~
```

The fix is simple, just use an uint32_t instead of an int32_t.